### ISSUE TITLE
New addresses every time

### ISSUE THREAD

**Issue by kopykatA** [ALQO-Universe/ALQO#15]
Every time I open the wallet a NEW address is created.
That behavior appears on latest 6.1 wallet. Please fix.

**Comment by barrystyle** [comment]
![ddmdDT9p3K](https://user-images.githubusercontent.com/14147070/70853506-db14ad00-1ee9-11ea-952c-0b5b7aea239c.gif)

**Comment by barrystyle** [comment]
Isn't occuring on build v6.1.0.0-bef46ae8d, which has been out for a few days now..

**Comment by CoinKd** [comment]
Hi,
still occuring on my alqo-qt.exe client, build v6.1.0.0-bef46ae8d, downloaded today.
