### ISSUE TITLE
PIVX name appears in a debug console after "getinfo" command

### ISSUE THREAD

**Issue by tomwrx** [ALQO-Universe/ALQO#16]
In a new wallet, when i type "getinfo" in a debug console, some information contains pivx instead of alqo, e.g.

== Pivx ==
checkbudgets
createmasternodebroadcast "command" ( "alias")
createmasternodekey

or 

== Wallet ==
addmultisigaddress nrequired ["key",...] ( "account" )
autocombinerewards enable ( threshold )
backupwallet "destination"
bip38decrypt "pivxaddress" "passphrase"
bip38encrypt "pivxaddress" "passphrase"

and etc.

**Comment by barrystyle** [comment]
Resolved in https://github.com/ALQO-Universe/ALQO/commit/c90346811dbbd60e87cb4b0c158f541480d59d16
