### ISSUE TITLE
Wallet sync stops requiring restart of wallet or alqod

### ISSUE THREAD

**Issue by nodecheck** [ALQO-Universe/ALQO#18]
### Describe the issue

QT Wallet, alqod stop syncing after an indeterminate amount of time, requiring alqod to be restarted or to restart the QT Wallet.  On restart, sync then works again, but can fail again later, requiring another restart.

### Can you reliably reproduce the issue?

So far has happened to be 3 or 4 times after each restart.

#### If so, please list the steps to reproduce below:
1. Run wallet.  Wait some time.
2. Check blockheight and notice it's behind/no longer syncing.
3. Restart wallet, starts syncing again.

Alqo block explorer also seems to have this problem as also has stopped syncing.  So doesn't to be an issue for not using pre-compiled binaries, or self-compiling, as one of my Ubuntu 18.04 machines doesn't have the symptoms, and yet the same binaries on the other Ubuntu 18.04 stops syncing.

### What version of ALQO are you using?
Latest wallet, self-compiled.

### Machine specs:
- OS: Ubuntu
- CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (although happens on multiple machines) / Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
- RAM: 32GB / 64GB
- Disk size: 480GB SSD / 2TB HDD
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
Am replicating the problem now with a clean debug.log to upload shortly.

**Comment by nodecheck** [comment]
Attached debug.log
[debug.log](https://github.com/ALQO-Universe/ALQO/files/3963876/debug.log)

**Comment by barrystyle** [comment]
The debug.log you've attached just shows a normal session; doesnt fall behind and keeps up with the network?

**Comment by nodecheck** [comment]
You can see some issues with errors accepting blocks.

```
2019-12-14 13:34:32 ERROR: CheckBlock : Couldn't find masternode/budget payment
2019-12-14 13:34:32 ERROR: ProcessNewBlock : CheckBlock FAILED for block db52a9569764fb5af88d7b5eb57298b275e155297d703d2d2e596798fbe93d8e
```

this obviously stops it from then downloading further.  Shutting down and restarting the wallet then allows it to continue normally.  Just wondering why this is happening?  I had it 4/5 times on my laptop, and 2/3 times on a server running alqod.

**Comment by barrystyle** [comment]
This means that your node doesnt have a full list of mastenodes/payments to validate against.. if you want to compile against the latest current commit (https://github.com/ALQO-Universe/ALQO/commit/d4d958e4f8bee1f6b3d90a1534a1e282fab54c41) - you'll find this won't be an issue anymore..

**Comment by nodecheck** [comment]
OK thanks, will update in the morning as midnight here now and will let you know if all stabilised with the new release.

**Comment by nodecheck** [comment]
Actually it's far worse with this release.  Compiled the nodes last night, restarted.  Stuck on block, and restarted and now won't sync and download past blocks 8185 or 8187 despite having connections and the blockhash being OK.  The node with 6.1 has higher blocks and matches the explorer as I didn't upgrade that one last night.  So generally, wallet have sync problems.

**Comment by nodecheck** [comment]
Reindex also doesn't help, reindex finished and stuck at block 300.  Deleted the chain from my test node, and now it's synced fine.  For the other one, also deleted, but stuck at block 300 and not syncing any further.  Pretty bad really.

**Comment by nodecheck** [comment]
[debug.log](https://github.com/ALQO-Universe/ALQO/files/3964783/debug.log)

**Comment by barrystyle** [comment]
Resolves the new issue https://github.com/ALQO-Universe/ALQO/commit/37571196d30cbdaed335d590d89797040b33d816

**Comment by ianw1974** [comment]
OK, compiling now just pulled and got the new chainparams* and main.cpp.

**Comment by nodecheck** [comment]
Seems to be working so far today anyway.  Looking good!

**Comment by barrystyle** [comment]
https://github.com/ALQO-Universe/ALQO/releases/tag/v6.3.0.0-c7fc25cad

No problems..
