### ISSUE TITLE
windowsize too large on linux

### ISSUE THREAD

**Issue by skyeatshorizon** [ALQO-Universe/ALQO#20]
### Describe the issue
Once the qt wallet is open the frame is way too large and cannot be resized. (linux)
However the window can be stretched to a larger size which does not solve the issue.
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. open linux wallet

### Expected behavior
window should be resizable.

### What version of ALQO are you using?
6.2

### Machine specs:
- OS: Ubuntu 18.04
- CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
- RAM: 8GB
- Disk size: 128GB
- Disk Type (HD/SDD): SSD

**Comment by barrystyle** [comment]
It is resizeable.. what is your screen resolution?

**Comment by skyeatshorizon** [comment]
1080p is my res
![Bildschirmfoto vom 2019-12-15 20-14-40](https://user-images.githubusercontent.com/50211860/70867624-b404bc80-1f77-11ea-8f89-95ff6758ff6d.png)

**Comment by jared-grey** [comment]
Is this issue still pending/open?

**Comment by skyeatshorizon** [comment]
@jared-grey I'll try the new version on my Linux machine and then I'll let you know
