### ISSUE TITLE
cursor jumps back to the end in the "Amount" field if you try to change the value

### ISSUE THREAD

**Issue by skyeatshorizon** [ALQO-Universe/ALQO#21]
### Describe the issue
Not mandatory but annoying.

#### If so, please list the steps to reproduce below:
1. Go to the send tab
2. enter something into Amount. like "1456"
3. place the cursor after 1. likethis: "1|456"
4. type "23"

### Expected behavior
You would expect: "123456"

### Actual behavior
but get "124563"

### What version of ALQO are you using?
6.3

### Machine specs:
- OS: Win10
- CPU: intel i5
- RAM: 16GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

**Comment by barrystyle** [comment]
Resolved in 0be96045ebe11ee48b1d2ecc76141d593c5d7eaa
