### ISSUE TITLE
ALQO 6.4 crashes on MAC when locking the wallet

### ISSUE THREAD

**Issue by Elkmar** [ALQO-Universe/ALQO#22]
### Describe the issue
ALQO 6.4 crashes on MAC (did not check on windows) when locking the wallet

#### If so, please list the steps to reproduce below:
1. Launch the 6.4 wallet on MAC (did not check on Windows)
2. Unlock it via the Icon
3. Lock it

### Expected behavior
The client should not crash

### Actual behavior
The client crashes

### What version of ALQO are you using?
ALQO 6.4, MAC, official binaries

**Comment by jared-grey** [comment]
This will be patched in the ver 6.5 release.
