### ISSUE TITLE
ALQO 6.4 crashes on Windows 10 when locking the wallet

### ISSUE THREAD

**Issue by dergaertner** [ALQO-Universe/ALQO#23]
### Describe the issue
ALQO 6.4 crashes on Windows 10 when locking the wallet. Probably related to #22
#### If so, please list the steps to reproduce below:
1. Start the Wallet
2. Open debug console
3. Type "walletlock"
4. Hit Enter
5. Wallet crashes

### Expected behavior
The wallet should be locked and still running.

### Actual behavior
The wallet crashes.

### What version of ALQO are you using?
Official binary: v6.4.0.0-7d5f56499

### Machine specs:
- OS: Windows 10 Pro
- CPU: Intel i3-6100U
- RAM: 32GB
- Disk size: 222GB
- Disk Type (HD/SSD): SSD

### Any extra information that might be useful in the debugging process.
The wallet doesn't need to be unlocked before. There is no error message and the debug.log shows no unusual entries. Attached the Windows Error Report from the Windows Event Viewer.
[Windows Error Report.txt](https://github.com/ALQO-Universe/ALQO/files/4242300/Windows.Error.Report.txt)

**Comment by jared-grey** [comment]
This will be patched in the ver 6.5 release.
