### ISSUE TITLE
Excess Logging

### ISSUE THREAD

**Issue by captaingeeky** [ALQO-Universe/ALQO#34]
https://github.com/ALQO-Universe/ALQO/blob/dfadacbab94c0b19e72dfd77482781b8b6f2eed1/src/kernel.cpp#L370

Make this error only write to the debug.log if the -debug flag is used to launch daemon. It is clogging up the debug file and confusing users.

**Comment by BlockMechanic** [comment]
This is resolved in https://github.com/ALQO-Universe/ALQO/pull/38
