### ISSUE TITLE
Keypool size

### ISSUE THREAD

**Issue by captaingeeky** [ALQO-Universe/ALQO#35]
https://github.com/ALQO-Universe/ALQO/blob/dfadacbab94c0b19e72dfd77482781b8b6f2eed1/src/wallet/wallet.cpp#L2706

Currently generating 1000 keys on launch, this is slow and not useful without z-type assets. Let's agree on a number of 250 or 500 and have it reduced.

**Comment by jared-grey** [comment]
Hmm. 250 is plenty. Agreed? @BlockMechanic @captaingeeky @raptor1001?

**Comment by BlockMechanic** [comment]
250 agreed

**Comment by BlockMechanic** [comment]
Resolved in https://github.com/ALQO-Universe/ALQO/pull/38
