### ISSUE TITLE
Windows 6.5 version - Wallet freezes on start.

### ISSUE THREAD

**Issue by meraki10** [ALQO-Universe/ALQO#37]
This issue tracker is only for technical issues related to ALQO.
General ALQO questions and/or support requests and are best directed to the [ALQO Discord](https://discord.gg/TbJdXFs).

### Describe the issue
Locked Wallet freezes on start. Have tried on two different machines. See screenshot. 

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behavior
Wallet should sync.

### Actual behavior
Wallet works find the 5-7 seconds, then freezes. 

### Screenshots.
![alqo](https://user-images.githubusercontent.com/67902436/86584378-706cb100-bfa2-11ea-9eaf-0ac4e3189e5c.png)

### What version of ALQO are you using?
Windows 6.5 version

### Machine specs:
- OS: Windows
- CPU: Intel(R) Core(TM) i5-2450 CPU@ 2.5GHz 
- RAM: 8Gb
- Disk size: 1TB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by BlockMechanic** [comment]
hi @meraki10 , can you please provide more details please, like the last section of your debug log and a complete screenshot. Were you running any additional programs ?
Is it a new wallet file or old ? How big is it in MB ?
Was your internet connection active ?

**Comment by meraki10** [comment]
Hey, so this is what i did. I remember there were issues syncing locked wallets in 6.4 version also. So i just deleted my wallet.dat file and restarted the wallet. And voila, it fully got synchronized. I closed and restarted the wallet several times and it ran just fine.

After having tested that the newly created wallet is working fine, I deleted and replaced it with my backup wallet.dat which is pass protected. And as soon as i start the wallet(although i was just able to see my balance), it freezes again. 
![alqoUntitled](https://user-images.githubusercontent.com/67902436/87031451-cb034880-c200-11ea-966b-6ddcb3d3ef9c.png)

I figured that it might be my wallet file that is corrupted, so once again delted the pass protected wallet file and re ran the alqo wallet hoping that the wallet should run just fine as it did before when i had deleted my wallet file. However this time again it freezes on start and i keep getting warning to keep checking my pc's date(which is update as per internet time).
![alqoUntitled1](https://user-images.githubusercontent.com/67902436/87032273-fc304880-c201-11ea-932d-229ec0af9ea2.png)

**Comment by meraki10** [comment]
Happy to announce i was able to resolve this by following steps:

1. Delete original wallet.dat file(take backup for later use).
2. Reset time settings - Both time and time zone(disable and re enable it).
3. Rerun wallet, a new wallet file is created and wallet syncs properly.
4. Replace new wallet.dat with my backup file.

PS- For some reason the above process only worked when i created a new wallet.dat file. In first attempt i tried with my original wallet file but wallet would not sync.
