### ISSUE TITLE
Wallet: Error Screen Formatting

### ISSUE THREAD

**Issue by jared-grey** [ALQO-Universe/ALQO#40]
Whenever a user has an open wallet and tries to open a second instance of the wallet, an error message appears.
This error message is white on white text and is difficult to see.

**Comment by BlockMechanic** [comment]
Seen. Will attempt to reproduce.

**Comment by BlockMechanic** [comment]
How is the instance being created? separate folder ?

**Comment by jared-grey** [comment]
> How is the instance being created? separate folder ?

 By clicking on the executable, while a current instance is running.

**Comment by imyugioh** [comment]
@BlockMechanic I am fixing it. no worries
