### ISSUE TITLE
QT window too tall for a notebook screen (1366x768 pixels)

### ISSUE THREAD

**Issue by walkjivefly** [ALQO-Universe/ALQO#7]
### Describe the issue
QT wallet window too tall for a notebook screen and can't be resized smaller.

#### If so, please list the steps to reproduce below:
1. Run v6 alqo-qt
2.
3.

### Expected behavior
Window should fit on screen, and be resizeable

### Actual behavior
Window is too tall for screen. Some information is lost.

### Screenshots.
![Screenshot_2019-12-10_20-02-50](https://user-images.githubusercontent.com/17745270/70531732-1f214e00-1b88-11ea-8890-2655895292e8.png)

### What version of PIVX Core are you using?
ALQO version v6.1.0.0-6774363c2
self-compiled

### Machine specs:
- OS: MX 18 linux
- CPU: Core i5
- RAM: 16GB
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

**Comment by barrystyle** [comment]
Hey mate,
Did you want to try branch 'reduceminimumheight-ui' and let me know if this resolves the issue?
https://github.com/ALQO-Universe/ALQO/commits/reduceminimumheight-ui
james

**Comment by walkjivefly** [comment]
Hmm,  fFirstRun probably shouldn't be set unconditionally true in init.cpp. Anyway, blitzed wallet and  restarted and window fits on screen and can even be resized down a bit. Thank you.
![Screenshot_2019-12-12_01-18-07](https://user-images.githubusercontent.com/17745270/70648350-76551a80-1c7d-11ea-8acf-0753de7be49f.png)
